# Generated by Django 5.1.4 on 2024-12-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterField(
            model_name='company',
            name='api_token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='external_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='open_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='signer',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='signer',
            name='external_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='signer',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='signer',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
