# Generated by Django 5.1.4 on 2024-12-19 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_company_options_alter_company_api_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='signer',
            name='document_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.document', null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signer',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
