# Generated by Django 5.1.4 on 2024-12-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_document_created_at_document_last_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
