# Generated by Django 5.1.4 on 2024-12-20 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_document_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at']},
        ),
    ]
